export const REGISTRATION_BEGINS = 'REGISTRATION_BEGINS';
export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';
export const REGISTRATION_REJECTED = 'REGISTRATION_REJECTED';
export const LOGIN_BEGINS = 'LOGIN_BEGINS';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';
