export const REGISTRATION_BEGINS = 'REGISTRATION_BEGINS';
export const REGISTRATION_SUCCESSFUL = 'REGISTRATION_SUCCESSFUL';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';
export const REGISTRATION_REJECTED = 'REGISTRATION_REJECTED';
